modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/CreativeMD/LittleTiles/issues"
logoFile="littletiles.png"
license="GNU General Public License v3.0"

[[mods]]
	modId="littletiles"
	version="${file.jarVersion}"
	displayName="LittleTiles"
	displayURL="https://minecraft.curseforge.com/projects/littletiles"
	authors="CreativeMD"
	description='''#BuildItYourself'''

[[dependencies.littletiles]]
	modId="creativecore"
	mandatory=true
	ordering="NONE"
	side="BOTH"
	versionRange="[2.10.20,)"